### ISSUE TITLE
C1T - Missing `robot_state_publisher` package

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-base#88]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

`carma-base` is missing the `robot_state_publisher` package, which is used by downstream packages for publishing static transforms.

### Carma version where this issue was discovered

Affects the `noetic-f1tenth/develop` branch.

### Expected behavior
`carma-base` builds and installs `robot_state_publisher` package.

### Actual behavior

`carma-base` does not build and install `robot_state_publisher` package.

### Steps to reproduce the actual behavior

1. Examine the `carma-base` `Dockerfile`

### Related work

usdot-fhwa-stol/carma-platform#1378

**Comment by msmcconnell** [comment]
Resolved by above PR
